version: '3.8'

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2002:3000'
            - '2003:3001'
        restart: always
        env_file:
            - .env
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
