version: '3.8'

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2002:3000'
            - '2003:3001'
        restart: always
        environment:
            - VITE_API_URL=http://10.2.10.17:3001
            - NODE_ENV=production
            - HTTPS=true
            - PORT=3002
            - PG_USER=app_trademkt
            - PG_HOST=10.2.10.49
            - PG_DATABASE=postgres
            - PG_PASSWORD=Please_Dont_Stop_Music
            - PG_PORT=5432
            - ORACLE_USER=tapajos
            - ORACLE_PASSWORD=tapajosteste
            - ORACLE_CONNECT_STRING=10.2.3.91/tpjp
            - SQL_USER=sinteg
            - SQL_PASSWORD=@sinteg123
            - SQL_SERVER=10.2.1.55
            - SQL_DATABASE=DBSINTEG_HML
            - JWT_SECRET=
            - AWS_ACCESS_KEY_ID=AKIAYLYIABHP5ULXZ2HA
            - AWS_SECRET_ACCESS_KEY=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
            - AWS_REGION=us-east-1
            - S3_BUCKET_NAME=intranet-tapajos
            - AZURE_CLIENT_ID=4ca15e42-c2a0-41df-81cd-58f485551533
            - AZURE_TENANT_ID=1d390b0e-fddf-40eb-9c71-9aaab4f5c8d1
            - SECRET_KEY=93f7fea8e407169184cf8cdc6e7f01e
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
