name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Testar a URL do Cloudflare Tunnel
      - name: Test SonarQube Connection
        run: curl -v https://<random-id>.trycloudflare.com/api/system/status

      # Step 3: Executar o SonarQube Scan
      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://alternatively-tournaments-merchant-passenger.trycloudflare.com/