name: Build and Push Docker Image on Remote Server

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Build and Push Docker Image on Remote Server
              run: |
                  ssh -o StrictHostKeyChecking=no dev_tapajos@10.2.10.17 << 'EOF'
                  cd /home/dev_tapajos/intranet-tapajos/intranet-tapajos
                  docker build -t dev_tapajos/intranet-tapajos:latest .
                  docker push dev_tapajos/intranet-tapajos:latest
                  EOF
